<?php declare(strict_types=1);

namespace Test;

use App\Component\Product\Business\ProductBusinessFacade;
use App\Component\Product\Business\ProductBusinessFacadeInterface;
use App\Component\Product\Persistence\Mapper\ProductMapper;
use App\Component\Product\Persistence\Mapper\ProductMapperInterface;
use App\Component\ProductCsv\Business\CsvImporter;
use App\Shared\Dto\ProductDataTransferObject;
use App\System\DI\Container;
use App\System\DI\DependencyProvider;
use Generated\Product;
use PHPUnit\Framework\TestCase;
use Propel\Runtime\Propel;

class CsvImporterTest extends TestCase
{

    private CsvImporter $csvImporter;
    private ProductMapperInterface $productMapper;
    private ProductBusinessFacadeInterface $productBusinessFacade;

    protected function setUp(): void
    {
        parent::setUp();
        $container = new Container();
        $containerProvider = new DependencyProvider();
        $containerProvider->providerDependency($container);

        $this->csvImporter = new CsvImporter($container);
        $this->productMapper = new ProductMapper();
        $this->productBusinessFacade = new ProductBusinessFacade($container);
    }

    protected function tearDown(): void
    {
        $con = Propel::getConnection();
        $sql = "TRUNCATE TABLE Products";
        $stmt = $con->prepare($sql);
        $stmt->execute();

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testLoadCsvData(): void
    {
        $path = __DIR__ . '/../../../../../readyData.csv';
        $this->csvImporter->loadCsvData($path);
    }

    public function testSaveAsCsvDto(): void
    {
        $path = __DIR__ . '/../../../CsvFile/csvDataInsert.csv';
        $records = $this->csvImporter->loadCsvData($path);
        $csvDtoList = $this->csvImporter->saveAsCsvDto($records);

        $productDtoList = [];
        foreach ($csvDtoList as $csvDto) {
            $productDtoList[] = $this->productMapper->mapFromCsv($csvDto);
        }

        foreach ($productDtoList as $product) {
            self::assertInstanceOf(ProductDataTransferObject::class, $product);
            $this->productBusinessFacade->save($product);
            //  Cannot insert a value for auto-increment primary key
            // allowPkInsert=true  into <table> schema.xml
        }

        $productListFromDb = $this->productBusinessFacade->getProductList();

        self::assertCount(5, $productListFromDb);

        foreach ($csvDtoList as $csvDto)
        {
            $productFromDb = $this->productBusinessFacade->getProductById($csvDto->getId());
            self::assertSame($csvDto->getId(), $productFromDb->getId());
            self::assertSame($csvDto->getName(), $productFromDb->getName());
            self::assertSame($csvDto->getDescription(), $productFromDb->getDescription());
        }
    }

    public function testUpdateSaveAsCsvDto(): void
    {
        $path = __DIR__ . '/../../../CsvFile/csvDataInsert.csv';
        $records = $this->csvImporter->loadCsvData($path);
        $csvDtoList = $this->csvImporter->saveAsCsvDto($records);

        $path = __DIR__ . '/../../../CsvFile/csvDataUpdate.csv';
        $records = $this->csvImporter->loadCsvData($path);
        $csvDtoList = $this->csvImporter->saveAsCsvDto($records);

        $productDtoList = [];
        foreach ($csvDtoList as $csvDto) {
            $productDtoList[] = $this->productMapper->mapFromCsv($csvDto);
        }

        foreach ($productDtoList as $product) {
            self::assertInstanceOf(ProductDataTransferObject::class, $product);
            $this->productBusinessFacade->save($product);
        }

        $productListFromDb = $this->productBusinessFacade->getProductList();

        self::assertCount(5, $productListFromDb);

        foreach ($csvDtoList as $csvDto)
        {
            $productFromDb = $this->productBusinessFacade->getProductById($csvDto->getId());
            self::assertSame($csvDto->getId(), $productFromDb->getId());
            self::assertSame($csvDto->getName(), $productFromDb->getName());
            self::assertSame($csvDto->getDescription(), $productFromDb->getDescription());
        }
    }


}
