<?php

use App\Controllers\Backend\CategoryController;
use App\Services\ViewService;
use Helper\ProductManagerTestHelper;

class CategoryControllerTest extends \Codeception\Test\Unit
{
    /**
     * @var \UnitTester
     */
    protected $tester;
    private ProductManagerTestHelper $productHelper;

    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub
        $this->productHelper = new ProductManagerTestHelper();
    }

    protected function _after()
    {
        parent::_after(); // TODO: Change the autogenerated stub
        $this->productHelper->deleteProducts();
    }


    public function testAction()
    {
        $listOfProducts = $this->productHelper->createProducts();

        $viewService = new ViewService();
        $category = new CategoryController($viewService);

        $category->action();
        dump($viewService->getParams());

        $temp = $viewService->getParams();
        self::assertArrayHasKey('productList', $temp);

        $one = $temp['productList'][2];
        self::assertSame(2, $one->getId());
        self::assertSame('mark', $one->getName());
    }
}