<?php declare(strict_types=1);

namespace Test\phpunit\Component\User\Communication\Controllers;

use App\Component\User\Communication\Controllers\Backend\UsersListController;
use App\System\DI\Container;
use App\System\DI\DependencyProvider;
use App\System\Smarty\ViewService;
use PHPUnit\Framework\TestCase;
use Test\phpunit\Helper\UserHelperTest;

class UsersListControllerTest extends TestCase
{
    private UserHelperTest $userHelperTest;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userHelperTest = new UserHelperTest();
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->userHelperTest->deleteTemporaryUsers();
    }

    public function testAction()
    {
        $listOfProducts = $this->userHelperTest->createTemporaryUsers();

        $container = new Container();
        $containerProvider = new DependencyProvider();
        $containerProvider->providerDependency($container);

        $viewService = $container->get(ViewService::class);

        $usersList = new UsersListController($container);

        $usersList->action();
        //dump($viewService->getParams());

        $temp = $viewService->getParams();
        self::assertArrayHasKey('userList', $temp);

        $one = $temp['userList'][2];
        self::assertSame(2, $one->getId());
        self::assertSame('Mark', $one->getUserName());
        self::assertSame('b', $one->getPassword());
        self::assertSame('Customer', $one->getUserRole());
    }

}
