<?php declare(strict_types=1);

namespace Test;

use App\Component\User\Persistence\Models\UserManager;
use App\Component\User\Persistence\Models\UserRepository;
use App\Shared\Dto\UserDataTransferObject;
use App\System\DI\Container;
use App\System\DI\DependencyProvider;
use PHPUnit\Framework\TestCase;
use Test\phpunit\Helper\UserHelperTest;

class UserManagerTest extends TestCase
{
    private UserHelperTest $userHelper;
    private Container $container;

    protected function setUp(): void
    {
        parent::setUp();
        $this->container = new Container();
        $containerProvider = new DependencyProvider();
        $containerProvider->providerDependency($this->container);
        $this->userHelper = new UserHelperTest();
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->userHelper->deleteTemporaryUsers();
    }

    public function testSaveInsert(): void
    {
        $userDataTransferObject = new UserDataTransferObject();
        $userDataTransferObject->setUserName('Filip');
        $userDataTransferObject->setPassword('e');
        $userDataTransferObject->setUserRole('Customer');

        $userManager = $this->container->get(UserManager::class);
        $actualValue = $userManager->save($userDataTransferObject);

        $userRepository = $this->container->get(UserRepository::class);
        $valueFromDatabase = $userRepository->getUser($actualValue->getUserName(), $actualValue->getPassword());

        self::assertSame('Filip', $valueFromDatabase->getUserName());
        self::assertSame('e', $valueFromDatabase->getPassword());
        self::assertSame('Customer', $valueFromDatabase->getUserRole());
        $this->userHelper->deleteTemporaryUsers();
    }

    public function testSaveUpdate(): void
    {
        $listOfUsers = $this->userHelper->createTemporaryUsers();

        $userDataTransferObject = new UserDataTransferObject();
        $userDataTransferObject->setId($listOfUsers[2]->getId());
        $userDataTransferObject->setUserName('William');
        $userDataTransferObject->setPassword('d');
        $userDataTransferObject->setUserRole('Customer');

        $userManager = $this->container->get(UserManager::class);
        $actualValue = $userManager->save($userDataTransferObject);

        $userRepository = $this->container->get(UserRepository::class);
        $listFromDatabase = $userRepository->getUser($userDataTransferObject->getUserName(), $userDataTransferObject->getPassword());


        self::assertSame($userDataTransferObject->getId(), $listFromDatabase->getId());
        self::assertSame($userDataTransferObject->getUserName(), $listFromDatabase->getUserName());
        self::assertSame($userDataTransferObject->getPassword(), $listFromDatabase->getPassword());
    }

    public function testDelete(): void
    {
        $this->userHelper->createTemporaryUsers();
        $userRepository = $this->container->get(UserRepository::class);
        $userDataTransferObject = $userRepository->getUserById(2);

        $userManager = $this->container->get(UserManager::class);
        $userManager->delete($userDataTransferObject);

        self::assertNull($userRepository->getUserById(2));
    }
}
