<?php declare(strict_types=1);

namespace Test;

use App\Component\Category\Persistence\Models\CategoryManager;
use App\Component\Product\Persistence\Models\ProductManager;
use App\Component\Product\Persistence\Models\ProductRepository;
use App\Shared\Dto\CategoryDataTransferObject;
use App\Shared\Dto\ProductDataTransferObject;
use App\System\DI\Container;
use App\System\DI\DependencyProvider;
use Generated\Category;
use PHPUnit\Framework\TestCase;
use Test\phpunit\Helper\CategoryHelperTest;
use Test\phpunit\Helper\ProductHelperTest;

class ProductManagerTest extends TestCase
{
    private ProductHelperTest $productHelper;
    private Container $container;
    private CategoryHelperTest $categoryHelper;

    protected function setUp(): void
    {
        parent::setUp();
        $this->container = new Container();
        $containerProvider = new DependencyProvider();
        $containerProvider->providerDependency($this->container);

        $this->productHelper = new ProductHelperTest();
        $this->categoryHelper = new CategoryHelperTest();

        $this->categoryHelper->createTemporaryCategories();
    }

    protected function tearDown(): void
    {
        $this->categoryHelper->deleteTemporaryCategories();
        $this->productHelper->deleteTemporaryProducts();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }


    public function testSaveInsert(): int
    {
        $productDataTransferObject = new ProductDataTransferObject();
        $productDataTransferObject->setName('filip');
        $productDataTransferObject->setDescription('lorem filip');

        $category = new CategoryDataTransferObject();
        $category->setId(1);
        $category->setName('tablet');
        $productDataTransferObject->setCategory($category);

        $productManager = $this->container->get(ProductManager::class);
        $actualValue = $productManager->save($productDataTransferObject);

        $productRepository = $this->container->get(ProductRepository::class);
        $valueFromDatabase = $productRepository->getProductById($actualValue->getId());

        self::assertSame('filip', $valueFromDatabase->getName());
        self::assertSame('lorem filip', $valueFromDatabase->getDescription());
        self::assertSame(1, $valueFromDatabase->getCategory()->getId());
        self::assertSame('tablet', $valueFromDatabase->getCategory()->getName());

        return $valueFromDatabase->getId();
    }

    public function testSaveUpdate(): int
    {
        $id = $this->testSaveInsert();

        $productDataTransferObject = new ProductDataTransferObject();
        $productDataTransferObject->setId($id);
        //$productDataTransferObject->setId($listOfProducts[2]->getId());
        $productDataTransferObject->setName('Unit Test');
        $productDataTransferObject->setDescription('Blbalbal');

        $category = new CategoryDataTransferObject();
        $category->setId(3);
        $category->setName('laptop');
        $productDataTransferObject->setCategory($category);

        $productManager = $this->container->get(ProductManager::class);
        $actualValue = $productManager->save($productDataTransferObject);

        $productRepository = $this->container->get(ProductRepository::class);
        $listFromDatabase = $productRepository->getProductById($productDataTransferObject->getId());

        self::assertSame($actualValue->getId(), $listFromDatabase->getId());

        self::assertSame($productDataTransferObject->getId(), $listFromDatabase->getId());
        self::assertSame($productDataTransferObject->getName(), $listFromDatabase->getName());
        self::assertSame($productDataTransferObject->getDescription(), $listFromDatabase->getDescription());
        self::assertSame($productDataTransferObject->getCategory()->getId(),
            $listFromDatabase->getCategory()->getId());
        self::assertSame($productDataTransferObject->getCategory()->getName(),
            $listFromDatabase->getCategory()->getName());

        return $listFromDatabase->getId();
    }

    public function testDelete(): void
    {
        $id = $this->testSaveUpdate();

        //$this->productHelper->createTemporaryProducts();
        $productRepository = $this->container->get(ProductRepository::class);
        $productDataTransferObject = $productRepository->getProductById($id);

        $productManager = $this->container->get(ProductManager::class);
        $productManager->delete($productDataTransferObject);

        self::assertNull($productRepository->getProductById($id));
    }

    public function testSaveWithOutCategory(): void
    {
        $productDataTransferObject = new ProductDataTransferObject();
        $productDataTransferObject->setName('filip');
        $productDataTransferObject->setDescription('lorem filip');

        $productManager = $this->container->get(ProductManager::class);
        $actualValue = $productManager->save($productDataTransferObject);

        $productRepository = $this->container->get(ProductRepository::class);
        $valueFromDatabase = $productRepository->getProductById($actualValue->getId());

        self::assertSame('filip', $valueFromDatabase->getName());
        self::assertSame('lorem filip', $valueFromDatabase->getDescription());
        self::assertNull($valueFromDatabase->getCategory());
    }
}
